from pyautogui import size

WINDOW_WIDTH = size()[0] / 5
WINDOW_HEIGHT = size()[1] / 2
DISPLAY_WIDTH = WINDOW_WIDTH / 1.02
DISPLAY_HEIGHT = WINDOW_HEIGHT / 1.125

BG_COLOUR = 'black'
FG_COLOUR = (60, 60, 60)